name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: windows
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: lukka/get-cmake@latest
    - name: configure and build
      uses: lukka/run-cmake@v3
      env:
        ENV_DIR: '${{ github.workspace }}'
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/ProjectFolder/CMakeLists.txt'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/build/'
    - name: run tests
      working-directory: ${{ github.workspace }}
      run: ctest --output-on-failure --test-dir ./build/tests
